version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.1.0

jobs:
  aws_cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Excute Create Cfn Stack
          command: |
            aws cloudformation create-stack --stack-name sample-stack --template-body file://service/infrastructure.yml
            aws cloudformation wait stack-create-complete --stack-name sample-stack

workflows:
  infrastructure-ci:
    jobs:
      - aws_cli
