version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.1.0

jobs:
  aws_cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Excute Create/Update Cfn Stack
          command: |
            set +e
            aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE | grep sample-stack
            if [ $? -eq 0 ]; then
              aws cloudformation update-stack --stack-name sample-stack --template-body file://service/infrastructure.yml
              if [ $? -eq 255 -o $? -eq 254 ]; then
                exit 0
              else
                aws cloudformation wait stack-update-complete --stack-name sample-stack
              fi
            elif [ $? -eq 1 ]; then
              aws cloudformation create-stack --stack-name sample-stack --template-body file://service/infrastructure.yml
              aws cloudformation wait stack-create-complete --stack-name sample-stack
            fi

workflows:
  infrastructure-ci:
    jobs:
      - aws_cli
