version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.1.0
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  aws_cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Excute Create/Update Cfn Stack
          command: |
            set +e
            aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE | grep sample-stack
            if [ $? -eq 0 ]; then
              aws cloudformation update-stack --stack-name sample-stack --template-body file://service/infrastructure.yml
              if [ $? -eq 255 -o $? -eq 254 ]; then
                exit 0
              else
                aws cloudformation wait stack-update-complete --stack-name sample-stack
              fi
            elif [ $? -eq 1 ]; then
              aws cloudformation create-stack --stack-name sample-stack --template-body file://service/infrastructure.yml
              aws cloudformation wait stack-create-complete --stack-name sample-stack
            fi
  ansible_playbook:
    executor: ansible-playbook/default
    steps:
      - checkout
      - ansible-playbook/install:
          version: 2.9.27
      - add_ssh_keys:
          fingerprints:
            - "62:6b:2b:c3:67:cd:b7:d0:c0:18:fc:dd:56:f4:94:19"
      - ansible-playbook/playbook:
          inventory: ANSIBLE_INVENTORY
          playbook: ansible/playbook.yml
          playbook-options: -u ec2-user
          private-key: ANSIBLE_SSH_KEY

workflows:
  infrastructure-ci:
    jobs:
      - aws_cli
      - ansible_playbook:
          requires:
            - aws_cli
